version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - laravel:/var/www/app:delegated
    networks:
      - laravel

  nginx:
    container_name: nginx
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - laravel:/var/www/app:delegated
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
    laravel:
